clone_depth: 1

platform:
 - x64
 - Win32

configuration:
  - Unicode Release
  - Unicode Debug

environment:
  boost_path: C:\projects\notepad-plus-plus\boost_1_55_0

install:
  - ps: if (Test-Path "boost_1_55_0.7z") {echo "file found in cache"} else {Invoke-WebRequest -OutFile boost_1_55_0.7z -UserAgent Wget/1.17.1 https://sourceforge.net/projects/boost/files/boost/1.55.0/boost_1_55_0.7z}
  - 7z x boost_1_55_0.7z 2>nul >nul

build_script:
  - cmd /k "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" < appveyor-build.cmd

cache:
 - boost_1_55_0.7z # preserve boost packages

after_build:
- ps: if (Test-Path "PowerEditor\bin64\Notepad++.exe") {Push-AppveyorArtifact "PowerEditor\bin64\Notepad++.exe" -FileName "Notepad++.bin64.exe"}
- ps: if (Test-Path "PowerEditor\visual.net\x64\Unicode Debug\Notepad++.exe") {Push-AppveyorArtifact "PowerEditor\visual.net\x64\Unicode Debug\Notepad++.exe" -FileName "Notepad++.bin64.debug.exe"}
- ps: if (Test-Path "PowerEditor\bin\Notepad++.exe" -FileName "Notepad++.exe") {Push-AppveyorArtifact "PowerEditor\bin\Notepad++.exe" -FileName "Notepad++.exe"}
- ps: if (Test-Path "PowerEditor\visual.net\Unicode Debug\Notepad++.exe") {Push-AppveyorArtifact "PowerEditor\visual.net\Unicode Debug\Notepad++.exe" -FileName "Notepad++.debug.exe"}
- ps: if (Test-Path "scintilla\bin\SciLexer.dll") {Push-AppveyorArtifact "scintilla\bin\SciLexer.dll"}

