version: 1.0.{build}
image: Visual Studio 2013


clone_depth: 1

platform:
  - x64
  - Win32

configuration:
  - Unicode Release
  - Unicode Debug

install:
  - if "%platform%"=="x64"   set "platformVCVarsAll=amd64"
  - if "%platform%"=="Win32" set "platformVCVarsAll=x86"
  - call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" %platformVCVarsAll%

build:
  verbosity: minimal

build_script:
  - cd c:\projects\notepad-plus-plus\scintilla\boostregex
  - if "%platform%"=="x64" (set "platformBoost=-x64") else (set "platformBoost=")
  - buildboost.bat "C:\Libraries\boost_1_62_0" %platformBoost%
  
  - cd c:\projects\notepad-plus-plus\scintilla\win32
  - if "%configuration:Debug=%"=="%configuration%" (set "configurationScintilla=DEBUG=1") else (set "configurationScintilla=")
  - nmake %configurationScintilla% -f scintilla.mak
  
  - cd c:\projects\notepad-plus-plus\PowerEditor\visual.net\
  - msbuild notepadPlus.vcxproj /p:configuration="%configuration%" /p:platform="%platform%"

after_build:
  - cd c:\projects\notepad-plus-plus\
  - ps: >-
      $nppFileName = "Notepad++.$env:PLATFORM.$env:CONFIGURATION.exe"
      $sciFileName = "SciLexer.$env:PLATFORM.$env:CONFIGURATION.dll"

      if ($env:PLATFORM -eq "x64" -and $env:CONFIGURATION -eq "Unicode Release") {
          Push-AppveyorArtifact "PowerEditor\bin64\Notepad++.exe" -FileName "$nppFileName"
      }

      if ($env:PLATFORM -eq "x64" -and $env:CONFIGURATION -eq "Unicode Debug") {
          Push-AppveyorArtifact "PowerEditor\visual.net\x64\Unicode Debug\Notepad++.exe" -FileName "$nppFileName"
      }

      if ($env:PLATFORM -eq "Win32" -and $env:CONFIGURATION -eq "Unicode Release") {
          Push-AppveyorArtifact "PowerEditor\bin\Notepad++.exe" -FileName "$nppFileName"
      }

      if ($env:PLATFORM -eq "Win32" -and $env:CONFIGURATION -eq "Unicode Debug") {
          Push-AppveyorArtifact "PowerEditor\visual.net\Unicode Debug\Notepad++.exe" -FileName "$nppFileName"
      }

      Push-AppveyorArtifact "scintilla\bin\SciLexer.dll" -FileName "$sciFileName"
