version: 8.4.{build}
image: Visual Studio 2022

#skip_commits:
#  files:
#    - PowerEditor/bin/*/*.xml
#    - PowerEditor/installer/*/*.xml

environment:
  matrix:
    - compiler: GCC
      platform: i686

    - compiler: GCC
      platform: x86_64

configuration:
    - Release
    #- Debug

before_build:
    - ps: |
        Write-Output "Build parameters:"
        Write-Output "Compiler : $env:compiler"
        Write-Output "Platform : $env:platform"
        Write-Output "Configuration : $env:configuration"

for:

- matrix:
    only:
      - compiler: GCC
  install:
    - set PATH=C:\msys64\usr\bin;%PATH%
    - if "%platform%" EQU "i686" set MSYSTEM=MINGW32
    - if "%platform%" EQU "x86_64" set MSYSTEM=MINGW64
    - if "%configuration%" EQU "Debug" set DEBUG=1
    # uncomment lines below to update packages to use latest gcc
    #- bash -lc "pacman --noconfirm -Syuu"
    #- bash -lc "pacman --noconfirm -Syuu"
    #- if "%platform%" EQU "i686" bash -lc "pacman --noconfirm -S mingw-w64-i686-gcc mingw-w64-i686-make"
    #- if "%platform%" EQU "x86_64" bash -lc "pacman --noconfirm -S mingw-w64-x86_64-gcc mingw-w64-x86_64-make"
    - if "%platform%" EQU "i686" set PATH=C:\msys64\mingw32\bin;%PATH%
    - if "%platform%" EQU "x86_64" set PATH=C:\msys64\mingw64\bin;%PATH%
    - ps: |
        Write-Output "Tools version:"
        Write-Output (((gcc --version) | select-object -first 1) + " " + (gcc -dumpmachine))
        Write-Output (mingw32-make --version) | select-object -first 1
        Write-Output (sh --version) | select-object -first 1
        Write-Output ""
  build_script:
    - @echo.
    - mingw32-make -f PowerEditor\gcc\makefile
    - @echo.

